name: "User stats 4geeks"
pipelines:
  - slug: "process_students_data_pipeline"
    sources:
      - cohort_user_with_projects_and_mentorships
      - cohorts-with-json-and-history-log
    destination: bigquery_users_stats
    transformations:
      - process_students_data